### ISSUE TITLE
desktop多文件的上传有点问题

### ISSUE THREAD

**Issue by forestsheep911** [cyaoc/kintone-dev-tools#7]
当我指定同app的desktop和mobile时，mobile回上传多文件，而desktop不会。
但没有mobile时，desktop也就正常了。

e.g.
我有
1.js
2.js

配置文件：

```
{
      "type": "app",
      "appid": 1,
      "folder": "",
      "upload": "desktop",
    },
    {
      "type": "app",
      "appid": 1,
      "folder": "",
      "upload": "mobile",
    }
```

我会得到
desktop下
1.js

mobile下
1.js
2.js

ps：css也是一样的

**Comment by cyaoc** [comment]
kdt的watch是以路径为唯一值进行上传的，同样的路径+多个配置 会导致设定间的冲突。
如果你要同时上传到desktop和mobile，请移除upload字段
如果你要分开上传不同的文件，请使用src字段或者新建一个folder
